pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {

            steps {
                withMaven(maven: 'maven_3_6_3'){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test'){
            steps {
              withMaven(maven: 'maven_3_6_3'){
                 sh 'mvn deploy'
              }
            }
        }
        stage('Deploy') {
            steps {
                sh 'make publish'
            }
        }
    }
}